# site settings
title: Evan Pratten
subtitle: retrylife
email: ewpratten@gmail.com
description: Computer wizard, student, <a href="https://github.com/frc5024">@frc5024</a> programming team lead, and radio enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://retrylife.ca
author:
street_address: 
city:
state:
zip_code:
country: 
phone:

about: >-
  I am a 16 year old programming student. I enjoy learning new concepts, building projects out of random ideas and obscure technologies, and working with new tools. 
  My projects range from building tools to help me with school work, and robotics, to radios and video production.

# Google analytics
analytic_track: UA-74118570-2

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 10

# permalink: /:title

# social settings
500px_url:
facebook_url:
github_url: https://github.com/ewpratten
gitlab_url: https://gitlab.com/u/ewpratten
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ewpratten

# build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jemoji