title: Evan Pratten
description: >- # this means to ignore newlines until "baseurl:"
  Computer wizard, student, <a href="https://frc5024.github.io">@frc5024</a> 
  programming team lead, and radio enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://retrylife.ca" # the base hostname & protocol for your site, e.g. http://example.com

about: >-
  I am a 17 year old programming student. I enjoy learning new concepts, 
  building projects out of random ideas and obscure technologies, and working with new tools. 
  My projects range from building tools to help me with school work, and robotics, to radios 
  and video production.

permalink: /blog/:year/:month/:day/:slug

ga_analytics: UA-74118570-2

# Social
twitter_username: ewpratten
insta_username: evanpratten
github_username:  ewpratten
devrant_username: ewpratten
gitlab_username: ewpratten
rtlgit_username: ewpratten
keybase_username: ewpratten

# Build settings
markdown: kramdown
kramdown:
  # input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

collections:
  notes:
    output: true
  music:
    output: true
    order:
      - retroactive.md
      - spamcalls.md
      - imagined.md


highlighter: rouge

sass:
    sass_dir: _sass

plugins:
  - jekyll-feed
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
